name: Node.js Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: echo "{\"url\":\"https://wellesley.powerschool.com\",\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\"}" > test-credentials.json
        name: Setup test-credentials.json
        env:
          USERNAME: ${{ secrets.username }}
          PASSWORD: ${{ secrets.password }}
      - run: yarn test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@whsha'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
